[project]
name = "fastapi-htmx-demo"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "fastapi>=0.111.0",
    "jinja2>=3.1.4",
    "databases[aiosqlite]>=0.9.0",
]
readme = "README.md"
requires-python = ">= 3.8"

[tool.rye.scripts]
serve = "fastapi run app/main.py"
watch = { cmd = "fastapi dev app/main.py", env = { ORDER_SYSTEM_DEBUG = 1 } }
tailwind-build = "./tailwindcss --minify -i app/styles.css -o static/styles.min.css"
tailwind-watch = "./tailwindcss --watch -i app/styles.css -o static/styles.css"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src"]
